server:
  port: 8580
  servlet:
    context-path: /springboot
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_study?characterEncoding=utf-8&useSSL=false
    password: rootroot
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      min-evictable-idle-time-millis: 60000
      pool-prepared-statements: true
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev #配置开发/生产环境的配置文件

